openapi: 3.1.0
info:
  title: Test API
  version: 1.0.0
servers:
  - url: https://api.example.com
x-speakeasy-retries:
  strategy: backoff
  backoff:
    initialInterval: 500
    maxInterval: 60000
    maxElapsedTime: 3600000
    exponent: 1.5
  retryConnectionErrors: true
  statusCodes:
    - 5XX
paths:
  /ping:
    get:
      summary: Ping
      responses:
        "200":
          description: OK
