workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/kw/kw/my-source
targets:
    my-target:
        target: python
        source: my-source
        output: .
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kw/kw/my-source-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
