workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: /home/user/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/kw/kw/my-source
targets:
    my-target:
        target: python
        source: my-source
        output: /home/user/sdk
